version: '2'
services:
  data:
    image: somatt/docker-sync:${DOCKER_SYNC_VERSION}
    ports:
      - 9010:9010

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: &mysql_pwd linkstore
      MYSQL_USER:          &mysql_user linkstore
      MYSQL_PASSWORD:      *mysql_pwd
      MYSQL_DATABASE:      &mysql_db linkstore
    ports:
      - 3307:3306

  mocks:
    image: somatt/docker-wiremock:2
    ports:
      - 8081:8080
    volumes:
      - ${PWD}/mocks/__files:/wiremock/__files:rw
      - ${PWD}/mocks/mappings:/wiremock/mappings:rw

  api:
    image: ${NODE_IMAGE}
    working_dir: /data
    command:     node --inspect=5858 service.js
    environment:
      WORKERS: 2
    ports:
      - 8080:5000
      - "5858-5860:5858-5860"
    volumes_from:
      - service:data:rw
    links:
      - mysql
      - mocks
    depends_on:
      - data
      - mysql
      - mocks

  node:
    image: ${NODE_IMAGE}
    working_dir: /data
    command:     /bin/bash -c "while [ 1 ]; do sleep 3600; done"
    volumes_from:
      - service:data:rw
    depends_on:
      - data
